- name: Install MySQL for production ready server
  user: root
  hosts: dbservers
  vars_files:
    - secrets.yml
  tasks:
    - name: Set MySQL root password before installing
      debconf: name="mysql-server" question="mysql-server/root_password" value="{{ mysql_root_pass }}" vtype="password"
    - name: Confirm MySQL root password before installing
      debconf: name="mysql-server" question="mysql-server/root_password_again" value="{{ mysql_root_pass }}" vtype="password"
    - name: test1
      apt:
        package:
            - default-mysql-server
            - default-mysql-client
            - python3-mysqldb
        state: present
        force: yes
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
      
    - name: Restart MariaDB
      service:
        name: mariadb
        state: restarted
        enabled: yes
        
    - name: Konfiguruj bind-address na 0.0.0.0
      lineinfile:
        path: "/etc/mysql/mariadb.conf.d/50-server.cnf"
        regexp: '^bind-address\s*='
        line: 'bind-address = 0.0.0.0'
        backup: yes

    - name: Restart MariaDB
      service:
        name: mariadb
        state: restarted
        enabled: yes
        

    - name: Create a new database called wordpress
      mysql_db:
        login_user: root
        login_password: "{{ db_server_root_pass }}"
        name: wordpress
        state: present
            

    - name: Configure new MySQL user called wpuser
      mysql_user:
        login_user: root
        login_password: "{{ db_server_root_pass }}"
        name: wpuser
        host: localhost
        state: present
        password: "{{ mysql_root_pass }}"
        priv: '*.*:ALL,GRANT'
        login_unix_socket: /var/run/mysqld/mysqld.sock

